/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.siag.swing;

import br.com.siag.beans.UsuarioBean;
import br.com.siag.dao.UsuarioDAO;
import br.com.siag.swing.gerencial.FrmPrincipalGer;
import br.com.siag.util.DAOFactory;
import br.com.siag.util.ValidarCPF;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import java.sql.Connection;
import java.sql.Date;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.xml.crypto.Data;

/**
 *
 * @author marcus
 */
public class frmLogin extends javax.swing.JFrame {

    private Connection conexao;

    /**
     * Creates new form frmLogin
     */
    public frmLogin() {
        initComponents();
        /**
         * SETAR ÍCONE DO FORMULÁRIO
         */
        URL url = this.getClass().getResource("ICO.png");
        Image iconeTitulo = Toolkit.getDefaultToolkit().getImage(url);
        this.setIconImage(iconeTitulo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPN_LOGIN = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        JTF_CPF_LOGIN = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        JC_DATANASC_LOGIN = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("AUTENTICAÇÃO DE SISTEMA");
        setResizable(false);

        JPN_LOGIN.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("CPF:");

        try {
            JTF_CPF_LOGIN.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel2.setText("Data de Nascimento:");

        jButton1.setText("Logar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/siag/imagens/cadeado.png"))); // NOI18N

        javax.swing.GroupLayout JPN_LOGINLayout = new javax.swing.GroupLayout(JPN_LOGIN);
        JPN_LOGIN.setLayout(JPN_LOGINLayout);
        JPN_LOGINLayout.setHorizontalGroup(
            JPN_LOGINLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPN_LOGINLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(JPN_LOGINLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPN_LOGINLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2)
                        .addComponent(jLabel1)
                        .addComponent(JTF_CPF_LOGIN, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(JC_DATANASC_LOGIN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        JPN_LOGINLayout.setVerticalGroup(
            JPN_LOGINLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPN_LOGINLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(JPN_LOGINLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(JPN_LOGINLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JTF_CPF_LOGIN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JC_DATANASC_LOGIN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JPN_LOGIN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JPN_LOGIN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            /**
             * MÉTODO RESPONSÁVEL POR AUTENTICAR USUÁRIO
             */

            //DAO E BEAN RESPONSÁVEL
            UsuarioDAO usuarioDAO = DAOFactory.criarUsuarioDAO(conexao);
            UsuarioBean user;

            //VARIAVEL QUE RECUPERA STRING DO FORMULÁRIO
            String cpf = JTF_CPF_LOGIN.getText().trim().replace("-", "").replace(".", "");

            //CONVERSÃO DO FORMATO DE DATA DE dd/MM/yyyy para yyyy-dd-MM
            SimpleDateFormat dateF = new SimpleDateFormat("yyyy-MM-dd");
            String data = dateF.format(JC_DATANASC_LOGIN.getDate());

            /**
             * REALIZA A VERIFICAÇÃO ATRAVÉS DO MÉTODO logar E VERIFICA SE O
             * RETORNO É DIFERENTE DE NULO SE O RETORNO FOR DIFERENTE DE NULO,
             * USUÁRIO FOI ENCONTRADO, SE NÃO, USUÁRIO NÃO ENCONTRADO
             */
            if (usuarioDAO.logar(cpf, java.sql.Date.valueOf(data)) != null && ValidarCPF.isValidCPF(cpf)) {
                //FECHAR FORMULÁRIO DE LOGIN
                dispose();

                //ATRIBUIÇÃO DOS VALORES DO USUÁRIO NA VARIAVEL user
                user = usuarioDAO.logar(cpf, java.sql.Date.valueOf(data));

                //VALIDAÇÃO DO TIPO DE USUÁRIO
                if (user.getTipo().equals("ATEND")) {
                    FrmPrincipal principal = new FrmPrincipal();
                    principal.setVisible(true);
                    //SETAR TEXTOS ESTÁTICOS REFERENTES AO ATENDENTE
                    principal.JL_NOME_USER.setText(user.getNome_usuario());
                    principal.JL_ID_USER.setText(String.valueOf(user.getCodigo()));
                    principal.JL_GUICHE_ATUAL.setText(String.valueOf(user.getCod_guiche()));
                    principal.JL_CATEGORIA_RESPONSAVEL.setText(user.getCategoria_servico());
                } else {
                    FrmPrincipalGer principalGerencial = new FrmPrincipalGer();
                    principalGerencial.setVisible(true);
                    principalGerencial.JL_NOME_USER.setText(user.getNome_usuario());
                }

            } else {
                //TRATAMENTO DE ERRO
                JOptionPane.showMessageDialog(null, "Usuário não encontrado !");
            }
        } catch (ClassNotFoundException | IllegalArgumentException | NullPointerException ex) {
            //TRATAMENTO DE EXCESSÃO
            JOptionPane.showMessageDialog(null, "Dados Inválidos - Tente Novamente  !" + ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser JC_DATANASC_LOGIN;
    private javax.swing.JPanel JPN_LOGIN;
    private javax.swing.JFormattedTextField JTF_CPF_LOGIN;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
